name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Create release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20.12.0
      - name: Install dependencies
        run: npm install
      - name: Publishing
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2.2.2
        if: success()
        with:
          files: |
            D:\a\Aerial-Launcher\Aerial-Launcher\out\make\squirrel.windows\x64\*
          tag_name: ${{github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

        
      
